Fix a regression, apply wasn't working for chord.
It was me actually adding this bug in a previous bugfix about eager run.
I thought these extra parameters were not used, but in reality they were
taking keys out from **options.

The exact error was this one:

File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py", line
169, in publish
publish = self.connection.ensure(self, publish, **retry_policy)
AttributeError: 'NoneType' object has no attribute 'ensure'